### PR TITLE
add:Hello Worldのイメージ

### PR DESCRIPTION
**Pull request by takaoooooo**
# プルリクエスト概要
- Hello Worldアプリのイメージを追加した
- ALBのセキュリティグループにインバウンドルールを追加した

## 変更点
- Hello Worldアプリのイメージを追加した
- ALBのセキュリティグループにインバウンドルールを追加した

## レビュー観点
- [x] リソースの命名規則に問題がないか
- [x] `terraform plan`の結果に問題ないか

### CODE REVIEW

**Comment by Takao-Yamasaki** [comment]
Terraform Plan <sup>[CI link]( https://ap-northeast-1.console.aws.amazon.com/codebuild/home?region=ap-northeast-1#/builds/aws-ecs-development-plan:589929b0-916f-4ae1-b393-39ddc0360212/view/new )</sup>
Plan detail via tfnotify

<pre><code>No changes. Your infrastructure matches the configuration.
</pre></code>

<details><summary>Details (Click me)</summary>

<pre><code>data.aws_iam_policy_document.my-app-task-execution-assume-policy: Reading...
aws_codedeploy_app.my-app-frontend: Refreshing state... [id=b923b8f8-63ad-40fc-80f7-acd46a6d6864:my-app-frontend]
aws_vpc.my-workspace-vpc: Refreshing state... [id=vpc-0e4e4d9582fcdd628]
data.aws_iam_policy_document.my-app-ecs-codedeploy-assume-policy: Reading...
aws_ecs_cluster.my-app-cluster: Refreshing state... [id=arn:aws:ecs:ap-northeast-1:786832920677:cluster/my-app-cluster]
aws_ecr_repository.my-app-frontend: Refreshing state... [id=my-app-frontend]
data.aws_iam_policy_document.my-app-task-execution-assume-policy: Read complete after 0s [id=1077804475]
aws_iam_role.my-app-task-execution-role: Refreshing state... [id=my-app-task-execution-role]
data.aws_iam_policy_document.my-app-ecs-codedeploy-assume-policy: Read complete after 0s [id=4250039221]
aws_iam_role.my-app-ecs-codedeploy-role: Refreshing state... [id=AWSCodeDeployRoleForECS]
aws_subnet.my-workspace-subnet-app-private1-a: Refreshing state... [id=subnet-0f577244718509274]
aws_security_group.my-app-frontend-sg: Refreshing state... [id=sg-05aab892f4d61b89c]
aws_route_table.my-workspace-rtb-private1-a: Refreshing state... [id=rtb-0a2c75dd50492778f]
aws_subnet.my-workspace-subnet-app-public1-c: Refreshing state... [id=subnet-0a687f42f6f7ad830]
aws_security_group.my-app-lb-sg: Refreshing state... [id=sg-061f8bc51c3330ec4]
aws_lb_target_group.my-app-frontend-tg-1: Refreshing state... [id=arn:aws:elasticloadbalancing:ap-northeast-1:786832920677:targetgroup/my-app-frontend-tg-1/9239510f5e1fd5ee]
aws_internet_gateway.my-workspace-igw: Refreshing state... [id=igw-0d2cd505dfe0388d1]
aws_lb_target_group.my-app-frontend-tg-2: Refreshing state... [id=arn:aws:elasticloadbalancing:ap-northeast-1:786832920677:targetgroup/my-app-frontend-tg-2/f6b8730c3c9f00a7]
aws_subnet.my-workspace-subnet-app-public1-a: Refreshing state... [id=subnet-0f898468f21b0e5d6]
aws_route_table.my-workspace-rtb-public1-a: Refreshing state... [id=rtb-0e87cda5fb0bd8687]
aws_vpc_security_group_ingress_rule.my-app-lb-sg-ingress-dev: Refreshing state... [id=sgr-0019c037cff5597ad]
aws_vpc_security_group_ingress_rule.my-app-frontend-sg-ingress: Refreshing state... [id=sgr-0af3fbcca9c23b01e]
aws_route_table_association.my-workspace-rt-assoc-private1-a: Refreshing state... [id=rtbassoc-01f7572f547ab82bb]
aws_lb.my-app-alb: Refreshing state... [id=arn:aws:elasticloadbalancing:ap-northeast-1:786832920677:loadbalancer/app/my-app-alb/5b6edd171116ea45]
aws_route_table_association.my-workspace-rt-assoc-public1-a: Refreshing state... [id=rtbassoc-0e3ea4b3c2f10f5dc]
aws_lb_listener.my-app-test-listener: Refreshing state... [id=arn:aws:elasticloadbalancing:ap-northeast-1:786832920677:listener/app/my-app-alb/5b6edd171116ea45/04dbd53220cf4d6d]
aws_lb_listener.my-app-production-listener: Refreshing state... [id=arn:aws:elasticloadbalancing:ap-northeast-1:786832920677:listener/app/my-app-alb/5b6edd171116ea45/73f84c6f1455c719]
aws_iam_role_policy_attachment.my-app-ecs-codedeploy-assume-policy: Refreshing state... [id=AWSCodeDeployRoleForECS-20240505035603815700000001]
aws_iam_role_policy_attachment.my-app-task-execution-policy: Refreshing state... [id=my-app-task-execution-role-20240504105527479900000001]
aws_ecs_task_definition.my-app-frontend: Refreshing state... [id=my-app-frontend]
aws_ecs_service.my-app-frontend-service: Refreshing state... [id=arn:aws:ecs:ap-northeast-1:786832920677:service/my-app-cluster/my-app-frontend-service]
aws_codedeploy_deployment_group.my-app-cluster-my-app-frontend-service: Refreshing state... [id=7dd6fc72-f998-4a8e-adb1-7ab490a7e69c]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration
and found no differences, so no changes are needed.

</pre></code></details>

**Comment by Takao-Yamasaki** [comment]
Terraform Plan <sup>[CI link]( https://ap-northeast-1.console.aws.amazon.com/codebuild/home?region=ap-northeast-1#/builds/aws-ecs-development-plan:ea7b6ce6-fc8c-4cfb-909e-171084858ca1/view/new )</sup>
Plan detail via tfnotify

<pre><code>Error: Incorrect attribute value type

  on security_group.tf line 11, in resource &#34;aws_security_group&#34; &#34;my-app-frontend-sg&#34;:
  11:     cidr_blocks = &#34;0.0.0.0/0&#34;

Inappropriate value for attribute &#34;cidr_blocks&#34;: list of string required.

Error: Incorrect attribute value type

  on security_group.tf line 33, in resource &#34;aws_security_group&#34; &#34;my-app-lb-sg&#34;:
  33:     cidr_blocks = &#34;0.0.0.0/0&#34;

Inappropriate value for attribute &#34;cidr_blocks&#34;: list of string required.

Error: Incorrect attribute value type

  on security_group.tf line 43, in resource &#34;aws_security_group&#34; &#34;my-app-lb-sg&#34;:
  43:     cidr_blocks = &#34;0.0.0.0/0&#34;

Inappropriate value for attribute &#34;cidr_blocks&#34;: list of string required.
</pre></code>

<details><summary>Details (Click me)</summary>

<pre><code>
Error: Incorrect attribute value type

  on security_group.tf line 11, in resource &#34;aws_security_group&#34; &#34;my-app-frontend-sg&#34;:
  11:     cidr_blocks = &#34;0.0.0.0/0&#34;

Inappropriate value for attribute &#34;cidr_blocks&#34;: list of string required.

Error: Incorrect attribute value type

  on security_group.tf line 33, in resource &#34;aws_security_group&#34; &#34;my-app-lb-sg&#34;:
  33:     cidr_blocks = &#34;0.0.0.0/0&#34;

Inappropriate value for attribute &#34;cidr_blocks&#34;: list of string required.

Error: Incorrect attribute value type

  on security_group.tf line 43, in resource &#34;aws_security_group&#34; &#34;my-app-lb-sg&#34;:
  43:     cidr_blocks = &#34;0.0.0.0/0&#34;

Inappropriate value for attribute &#34;cidr_blocks&#34;: list of string required.

</pre></code></details>

**Comment by Takao-Yamasaki** [comment]
Terraform Plan <sup>[CI link]( https://ap-northeast-1.console.aws.amazon.com/codebuild/home?region=ap-northeast-1#/builds/aws-ecs-development-plan:7a39b350-409c-4330-9a2c-45015c591636/view/new )</sup>
Plan detail via tfnotify

<pre><code>Error: Incorrect attribute value type

  on security_group.tf line 11, in resource &#34;aws_security_group&#34; &#34;my-app-frontend-sg&#34;:
  11:     cidr_blocks = &#34;0.0.0.0/0&#34;

Inappropriate value for attribute &#34;cidr_blocks&#34;: list of string required.

Error: Incorrect attribute value type

  on security_group.tf line 34, in resource &#34;aws_security_group&#34; &#34;my-app-lb-sg&#34;:
  34:     cidr_blocks = &#34;0.0.0.0/0&#34;

Inappropriate value for attribute &#34;cidr_blocks&#34;: list of string required.

Error: Incorrect attribute value type

  on security_group.tf line 44, in resource &#34;aws_security_group&#34; &#34;my-app-lb-sg&#34;:
  44:     cidr_blocks = &#34;0.0.0.0/0&#34;

Inappropriate value for attribute &#34;cidr_blocks&#34;: list of string required.
</pre></code>

<details><summary>Details (Click me)</summary>

<pre><code>
Error: Incorrect attribute value type

  on security_group.tf line 11, in resource &#34;aws_security_group&#34; &#34;my-app-frontend-sg&#34;:
  11:     cidr_blocks = &#34;0.0.0.0/0&#34;

Inappropriate value for attribute &#34;cidr_blocks&#34;: list of string required.

Error: Incorrect attribute value type

  on security_group.tf line 34, in resource &#34;aws_security_group&#34; &#34;my-app-lb-sg&#34;:
  34:     cidr_blocks = &#34;0.0.0.0/0&#34;

Inappropriate value for attribute &#34;cidr_blocks&#34;: list of string required.

Error: Incorrect attribute value type

  on security_group.tf line 44, in resource &#34;aws_security_group&#34; &#34;my-app-lb-sg&#34;:
  44:     cidr_blocks = &#34;0.0.0.0/0&#34;

Inappropriate value for attribute &#34;cidr_blocks&#34;: list of string required.

</pre></code></details>

**Comment by takaoooooo** [comment]
Terraform Plan <sup>[CI link]( https://ap-northeast-1.console.aws.amazon.com/codebuild/home?region=ap-northeast-1#/builds/aws-ecs-development-plan:2f68ccf2-054d-4867-ba07-b9db0c359cf2/view/new )</sup>
Plan detail via tfnotify

<pre><code>Plan: 1 to add, 2 to change, 3 to destroy.
</pre></code>

<details><summary>Details (Click me)</summary>

<pre><code>aws_vpc_security_group_ingress_rule.my-app-frontend-sg-ingress: Refreshing state... [id=sgr-0af3fbcca9c23b01e]
data.aws_iam_policy_document.my-app-task-execution-assume-policy: Reading...
aws_ecs_cluster.my-app-cluster: Refreshing state... [id=arn:aws:ecs:ap-northeast-1:786832920677:cluster/my-app-cluster]
aws_vpc.my-workspace-vpc: Refreshing state... [id=vpc-0e4e4d9582fcdd628]
aws_ecr_repository.my-app-frontend: Refreshing state... [id=my-app-frontend]
data.aws_iam_policy_document.my-app-task-execution-assume-policy: Read complete after 0s [id=1077804475]
data.aws_iam_policy_document.my-app-ecs-codedeploy-assume-policy: Reading...
aws_codedeploy_app.my-app-frontend: Refreshing state... [id=b923b8f8-63ad-40fc-80f7-acd46a6d6864:my-app-frontend]
aws_vpc_security_group_ingress_rule.my-app-lb-sg-ingress-dev: Refreshing state... [id=sgr-0019c037cff5597ad]
aws_iam_role.my-app-task-execution-role: Refreshing state... [id=my-app-task-execution-role]
data.aws_iam_policy_document.my-app-ecs-codedeploy-assume-policy: Read complete after 0s [id=4250039221]
aws_iam_role.my-app-ecs-codedeploy-role: Refreshing state... [id=AWSCodeDeployRoleForECS]
aws_subnet.my-workspace-subnet-app-public1-c: Refreshing state... [id=subnet-0a687f42f6f7ad830]
aws_lb_target_group.my-app-frontend-tg-1: Refreshing state... [id=arn:aws:elasticloadbalancing:ap-northeast-1:786832920677:targetgroup/my-app-frontend-tg-1/9239510f5e1fd5ee]
aws_lb_target_group.my-app-frontend-tg-2: Refreshing state... [id=arn:aws:elasticloadbalancing:ap-northeast-1:786832920677:targetgroup/my-app-frontend-tg-2/f6b8730c3c9f00a7]
aws_security_group.my-app-frontend-sg: Refreshing state... [id=sg-05aab892f4d61b89c]
aws_route_table.my-workspace-rtb-private1-a: Refreshing state... [id=rtb-0a2c75dd50492778f]
aws_subnet.my-workspace-subnet-app-public1-a: Refreshing state... [id=subnet-0f898468f21b0e5d6]
aws_subnet.my-workspace-subnet-app-private1-a: Refreshing state... [id=subnet-0f577244718509274]
aws_internet_gateway.my-workspace-igw: Refreshing state... [id=igw-0d2cd505dfe0388d1]
aws_security_group.my-app-lb-sg: Refreshing state... [id=sg-061f8bc51c3330ec4]
aws_route_table.my-workspace-rtb-public1-a: Refreshing state... [id=rtb-0e87cda5fb0bd8687]
aws_route_table_association.my-workspace-rt-assoc-private1-a: Refreshing state... [id=rtbassoc-01f7572f547ab82bb]
aws_route_table_association.my-workspace-rt-assoc-public1-a: Refreshing state... [id=rtbassoc-0e3ea4b3c2f10f5dc]
aws_lb.my-app-alb: Refreshing state... [id=arn:aws:elasticloadbalancing:ap-northeast-1:786832920677:loadbalancer/app/my-app-alb/5b6edd171116ea45]
aws_lb_listener.my-app-test-listener: Refreshing state... [id=arn:aws:elasticloadbalancing:ap-northeast-1:786832920677:listener/app/my-app-alb/5b6edd171116ea45/04dbd53220cf4d6d]
aws_lb_listener.my-app-production-listener: Refreshing state... [id=arn:aws:elasticloadbalancing:ap-northeast-1:786832920677:listener/app/my-app-alb/5b6edd171116ea45/73f84c6f1455c719]
aws_iam_role_policy_attachment.my-app-ecs-codedeploy-assume-policy: Refreshing state... [id=AWSCodeDeployRoleForECS-20240505035603815700000001]
aws_iam_role_policy_attachment.my-app-task-execution-policy: Refreshing state... [id=my-app-task-execution-role-20240504105527479900000001]
aws_ecs_task_definition.my-app-frontend: Refreshing state... [id=my-app-frontend]
aws_ecs_service.my-app-frontend-service: Refreshing state... [id=arn:aws:ecs:ap-northeast-1:786832920677:service/my-app-cluster/my-app-frontend-service]
aws_codedeploy_deployment_group.my-app-cluster-my-app-frontend-service: Refreshing state... [id=7dd6fc72-f998-4a8e-adb1-7ab490a7e69c]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  ~ update in-place
  - destroy
-/&#43; destroy and then create replacement

Terraform will perform the following actions:

  # aws_lb.my-app-alb will be updated in-place
  ~ resource &#34;aws_lb&#34; &#34;my-app-alb&#34; {
        id                                          = &#34;arn:aws:elasticloadbalancing:ap-northeast-1:786832920677:loadbalancer/app/my-app-alb/5b6edd171116ea45&#34;
        name                                        = &#34;my-app-alb&#34;
      ~ security_groups                             = [
          - &#34;sg-061f8bc51c3330ec4&#34;,
        ] -&gt; (known after apply)
        tags                                        = {
            &#34;Name&#34; = &#34;my-app-alb&#34;
        }
        # (21 unchanged attributes hidden)

        # (4 unchanged blocks hidden)
    }

  # aws_security_group.my-app-frontend-sg will be updated in-place
  ~ resource &#34;aws_security_group&#34; &#34;my-app-frontend-sg&#34; {
        id                     = &#34;sg-05aab892f4d61b89c&#34;
      ~ ingress                = [
          - {
              - cidr_blocks      = [
                  - &#34;0.0.0.0/0&#34;,
                ]
              - description      = &#34;&#34;
              - from_port        = 80
              - ipv6_cidr_blocks = []
              - prefix_list_ids  = []
              - protocol         = &#34;tcp&#34;
              - security_groups  = []
              - self             = false
              - to_port          = 80
            },
          - {
              - cidr_blocks      = [
                  - &#34;0.0.0.0/0&#34;,
                ]
              - description      = &#34;&#34;
              - from_port        = 9000
              - ipv6_cidr_blocks = []
              - prefix_list_ids  = []
              - protocol         = &#34;tcp&#34;
              - security_groups  = []
              - self             = false
              - to_port          = 9000
            },
          &#43; {
              &#43; cidr_blocks      = [
                  &#43; &#34;0.0.0.0/0&#34;,
                ]
              &#43; from_port        = 80
              &#43; ipv6_cidr_blocks = []
              &#43; prefix_list_ids  = []
              &#43; protocol         = &#34;tcp&#34;
              &#43; security_groups  = []
              &#43; self             = false
              &#43; to_port          = 80
            },
        ]
        name                   = &#34;my-app-frontend-sg&#34;
        tags                   = {}
        # (7 unchanged attributes hidden)
    }

  # aws_security_group.my-app-lb-sg must be replaced
-/&#43; resource &#34;aws_security_group&#34; &#34;my-app-lb-sg&#34; {
      ~ arn                    = &#34;arn:aws:ec2:ap-northeast-1:786832920677:security-group/sg-061f8bc51c3330ec4&#34; -&gt; (known after apply)
      ~ id                     = &#34;sg-061f8bc51c3330ec4&#34; -&gt; (known after apply)
      ~ ingress                = [
          &#43; {
              &#43; cidr_blocks      = [
                  &#43; &#34;0.0.0.0/0&#34;,
                ]
              &#43; description      = &#34;for Developer&#34;
              &#43; from_port        = 9000
              &#43; ipv6_cidr_blocks = []
              &#43; prefix_list_ids  = []
              &#43; protocol         = &#34;tcp&#34;
              &#43; security_groups  = []
              &#43; self             = false
              &#43; to_port          = 9000
            },
          &#43; {
              &#43; cidr_blocks      = [
                  &#43; &#34;0.0.0.0/0&#34;,
                ]
              &#43; description      = &#34;for User&#34;
              &#43; from_port        = 80
              &#43; ipv6_cidr_blocks = []
              &#43; prefix_list_ids  = []
              &#43; protocol         = &#34;tcp&#34;
              &#43; security_groups  = []
              &#43; self             = false
              &#43; to_port          = 80
            },
        ]
      ~ name                   = &#34;terraform-20240504105537718500000003&#34; -&gt; &#34;my-app-lb-sg&#34; # forces replacement
      ~ name_prefix            = &#34;terraform-&#34; -&gt; (known after apply)
      ~ owner_id               = &#34;786832920677&#34; -&gt; (known after apply)
      - tags                   = {} -&gt; null
      ~ tags_all               = {} -&gt; (known after apply)
        # (4 unchanged attributes hidden)
    }

  # aws_vpc_security_group_ingress_rule.my-app-frontend-sg-ingress will be destroyed
  # (because aws_vpc_security_group_ingress_rule.my-app-frontend-sg-ingress is not in configuration)
  - resource &#34;aws_vpc_security_group_ingress_rule&#34; &#34;my-app-frontend-sg-ingress&#34; {
      - arn                    = &#34;arn:aws:ec2:ap-northeast-1:786832920677:security-group-rule/sgr-0af3fbcca9c23b01e&#34; -&gt; null
      - cidr_ipv4              = &#34;0.0.0.0/0&#34; -&gt; null
      - from_port              = 80 -&gt; null
      - id                     = &#34;sgr-0af3fbcca9c23b01e&#34; -&gt; null
      - ip_protocol            = &#34;tcp&#34; -&gt; null
      - security_group_id      = &#34;sg-05aab892f4d61b89c&#34; -&gt; null
      - security_group_rule_id = &#34;sgr-0af3fbcca9c23b01e&#34; -&gt; null
      - tags_all               = {} -&gt; null
      - to_port                = 80 -&gt; null
    }

  # aws_vpc_security_group_ingress_rule.my-app-lb-sg-ingress-dev will be destroyed
  # (because aws_vpc_security_group_ingress_rule.my-app-lb-sg-ingress-dev is not in configuration)
  - resource &#34;aws_vpc_security_group_ingress_rule&#34; &#34;my-app-lb-sg-ingress-dev&#34; {
      - arn                    = &#34;arn:aws:ec2:ap-northeast-1:786832920677:security-group-rule/sgr-0019c037cff5597ad&#34; -&gt; null
      - cidr_ipv4              = &#34;0.0.0.0/0&#34; -&gt; null
      - from_port              = 9000 -&gt; null
      - id                     = &#34;sgr-0019c037cff5597ad&#34; -&gt; null
      - ip_protocol            = &#34;tcp&#34; -&gt; null
      - security_group_id      = &#34;sg-05aab892f4d61b89c&#34; -&gt; null
      - security_group_rule_id = &#34;sgr-0019c037cff5597ad&#34; -&gt; null
      - tags_all               = {} -&gt; null
      - to_port                = 9000 -&gt; null
    }

Plan: 1 to add, 2 to change, 3 to destroy.

─────────────────────────────────────────────────────────────────────────────

Note: You didn&#39;t use the -out option to save this plan, so Terraform can&#39;t
guarantee to take exactly these actions if you run &#34;terraform apply&#34; now.

</pre></code></details>

**Pull request merged**
